const photoSets = {
  digi: [
    { src: "digi/Filial project /14_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /15_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /23_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /18_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /08_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /17_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /10_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /11_prumprum.jpg", project: "Filial Project" },
    { src: "digi/Filial project /20_prumprum.jpg", project: "Filial Project" },
    { src: "digi/work/01_house.jpg", project: "House" },
    { src: "digi/work/07_house.jpg", project: "House" },
    { src: "digi/work/03_house.jpg", project: "House" },
    { src: "digi/work/08_house.jpg", project: "House" },
    { src: "digi/work/05_house.jpg", project: "House" },
    { src: "digi/work/02_house.jpg", project: "House" },
    { src: "digi/Work 2/21_angy.jpg", project: "Work 2" },
    { src: "digi/Work 2/36_angy.jpg", project: "Work 2" },
    { src: "digi/Work 2/30_angy.jpg", project: "Work 2" },
    { src: "digi/Work 2/18_angy.jpg", project: "Work 2" },
    { src: "digi/Work 2/27_angy.jpg", project: "Work 2" },
    { src: "digi/Work 2/12_angy.jpg", project: "Work 2" },
    { src: "digi/Work 2/11_angy.jpg", project: "Work 2" },
    { src: "digi/Work 2/07_angy.jpg", project: "Work 2" },
    { src: "digi/work 3/21_angy.jpg", project: "Work 3" },
    { src: "digi/work 3/14_angy.jpg", project: "Work 3" },
    { src: "digi/work 3/02_angy.jpg", project: "Work 3" },
    { src: "digi/work 3/26_angy.jpg", project: "Work 3" },
    { src: "digi/work 3/16_angy.jpg", project: "Work 3" },
    { src: "digi/work 3/25_angy.jpg", project: "Work 3" }
  ],
  film: [
    { src: "film/Project 2/000020980008.jpg", project: "Project 2" },
    { src: "film/Project 2/000020980037.jpg", project: "Project 2" },
    { src: "film/Project 2/2096-20.JPG", project: "Project 2" },
    { src: "film/Project 2/2096-21.JPG", project: "Project 2" },
    { src: "film/Project 2/2095-14.JPG", project: "Project 2" },
    { src: "film/Project 2/000020970006.jpg", project: "Project 2" },
    { src: "film/Project 2/000020970012.jpg", project: "Project 2" },
    { src: "film/Project 2/2095-3.jpg", project: "Project 2" },
    { src: "film/Project 2/2095-16.JPG", project: "Project 2" },
    { src: "film/Project 2/000020970019.jpg", project: "Project 2" },
    { src: "film/Project 2/2095-34.JPG", project: "Project 2" },
    { src: "film/Project 2/2096-12.JPG", project: "Project 2" },
    { src: "film/project 1/IMG_4139.JPG", project: "Project 1" },
    { src: "film/project 1/IMG_4152.JPG", project: "Project 1" },
    { src: "film/project 1/IMG_4153.JPG", project: "Project 1" },
    { src: "film/project 1/IMG_4151.JPG", project: "Project 1" },
    { src: "film/project 1/IMG_4242.JPG", project: "Project 1" },
    { src: "film/Filial Project film/IMG_4580.jpeg", project: "Filial Project Film" },
    { src: "film/Filial Project film/IMG_4579.jpeg", project: "Filial Project Film" },
    { src: "film/Filial Project film/IMG_4581.jpeg", project: "Filial Project Film" },
    { src: "film/Filial Project film/IMG_4574.jpeg", project: "Filial Project Film" },
    { src: "film/Filial Project film/IMG_4586.jpeg", project: "Filial Project Film" },
    { src: "film/Filial Project film/IMG_4572.jpeg", project: "Filial Project Film" },
    { src: "film/Filial Project film/IMG_4584.jpeg", project: "Filial Project Film" },
    { src: "film/Filial Project film/IMG_4585.jpeg", project: "Filial Project Film" }
  ],
  archive: [
    { src: "digi/Archive photo/P1000728.JPG", project: "Digital Archive" },
    { src: "digi/Archive photo/P1000846.JPG", project: "Digital Archive" },
    { src: "digi/Archive photo/P1000717.JPG", project: "Digital Archive" },
    { src: "digi/Archive photo/P1000919.JPG", project: "Digital Archive" },
    { src: "digi/Archive photo/P1010288.JPG", project: "Digital Archive" },
    { src: "digi/Archive photo/07_final.jpg", project: "Digital Archive" },
    { src: "digi/Archive photo/13_final.jpg", project: "Digital Archive" },
    { src: "digi/Archive photo/P1000749.JPG", project: "Digital Archive" },
    { src: "digi/Archive photo/15_final.jpg", project: "Digital Archive" },
    { src: "digi/Archive photo/10_final.jpg", project: "Digital Archive" },
    { src: "digi/Archive photo/04_final.jpg", project: "Digital Archive" },
    { src: "digi/Archive photo/09_final.jpg", project: "Digital Archive" },
    { src: "digi/Archive photo/P1000722.JPG", project: "Digital Archive" },
    { src: "digi/Archive photo/08_final.jpg", project: "Digital Archive" },
    { src: "film/Archive film/IMG_3285.JPG", project: "Film Archive" },
    { src: "film/Archive film/IMG_3283.JPG", project: "Film Archive" },
    { src: "film/Archive film/IMG_4149.JPG", project: "Film Archive" },
    { src: "film/Archive film/IMG_3299.JPG", project: "Film Archive" },
    { src: "film/Archive film/IMG_3301.JPG", project: "Film Archive" }
  ]
};
